ログインとサインアップのHTML/CSS
Variableavalanchezueha/chat pull request #6
Opened 2019-12-31 04:52 UTC by ma1105yuko

半角英数字のみ、などの条件は特に今回書かなかったです。

**PLEASE NOTE:**

This is only a issue tracker for issues related to the CakePHP Application Skeleton.
For CakePHP Framework issues please use this [issue tracker](https://github.com/cakephp/cakephp/issues).

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/cakephp/cakephp/blob/master/.github/CONTRIBUTING.md) guidelines when submitting a pull request. In particular, make sure existing tests still pass, and add tests for all new behavior. When fixing a bug, you may want to add a test to verify the fix.

2019-12-31 06:57 UTC, namida-neet requested changes
CSSで2箇所修正のコメントを書いてみました。

2019-12-31 06:57 UTC, namida-neet commented on design/style.css
> +/*LOG IN　＆　SIGN IN*/
たぶん、SIGN INではなく、SIGN UP？

2019-12-31 06:57 UTC, namida-neet commented on design/style.css
> +  }
ここから下の行、先頭にスペース入っているのが気になります。
細かくてすみません。

2019-12-31 07:30 UTC, y0shihiro commented on design/style.css
> +  }
こういうのはエディタの自動整形の機能使うとめっちゃ楽でいいと思うよー

2020-01-01 11:12 UTC, ma1105yuko commented on design/style.css
> +/*LOG IN　＆　SIGN IN*/
ご指摘の通りSIGN UP の間違いです！！

2020-01-01 11:15 UTC, ma1105yuko commented on design/style.css
> +  }
ありがとうございます！

2020-01-03 01:41 UTC, namida-neet approved these changes
みましたー

2020-01-03 01:54 UTC, merged